### ISSUE TITLE
'ant-prefix' 部分 ant样式不生效，你是怎么解决的呢？

### ISSUE THREAD

**Issue by J-DuYa** [sssonamuuu/react-typescript-base#1]
'ant-prefix' 部分 ant样式不生效，你是怎么解决的呢？

**Comment by sssonamuuu** [comment]
暂时就用antd啊，主要是icon这块不支持，其他都还能特殊处理一下

**Comment by sssonamuuu** [comment]
> 'ant-prefix' 部分 ant样式不生效，你是怎么解决的呢？

暂时就用antd啊，主要是icon这块不支持，其他都还能特殊处理一下
